### ISSUE TITLE
Horizontal version coming?

### ISSUE THREAD

**Issue by AseKarlsson** [svenove/OpenEPaperLink-HA-Pollen#1]
Hi,
Any plans for a Horizontal version (I have everything else in horizontal)?

Thanks,
Anders

**Comment by svenove** [comment]
No plans for horizontal, sorry. 
I have 6 others horizontal too, but this one is vertically mounted next to them. Fits fine next to two horizontal ones. :)

**Comment by AseKarlsson** [comment]
Fair and straight answer, Thanks!
